services:
  mockup-service:
    build: app
    image: python:3.12-slim
    restart: unless-stopped
    command: sh -c "watchmedo auto-restart --pattern='*.py' --recursive -- python main.py"
    volumes:
      - ./app/:/opt/python-projects/app/
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  redis:
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly no --save 60 1
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./caching:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 10s
      retries: 3

